package:
  name: hello-server
  version: 0.1.0
  description: friendly little webserver
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
      paths:
        - "*"

# This appears to be the settings we need to build on Wolfi as opposed to
# "plain" Alpine. Note that the packages are not like-for-like!
environment:
  contents:
    keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
    - https://packages.wolfi.dev/os
    packages:
      - ca-certificates-bundle
      - busybox
      - build-base
      - go

pipeline:
  - name: Build Go application
    runs: |
      CGO_ENABLED=0 go build -o "${{targets.destdir}}/usr/bin/hello-server" .
